[package]
name = "rustycam-node"
version = "0.1.0"
edition = "2022"

[dependencies]
retina = "0.4.1"
tokio = { version = "1.4.0", features = ["rt", "rt-multi-thread", "macros"] }
url = "2.2.1"
log = "0.4.8"